<?php

use Drupal\block\Entity\Block;

/**
 * @file
 * Install, update and uninstall functions for the hackdonalds module.
 */

/**
 * Implements hook_install().
 */
function hackdonalds_install() {
  /**
   * Disable default blocks 
   */
  $blocks = Block::loadMultiple(array('bartik_search', 'bartik_tools', 'bartik_footer', 'bartik_powered'));
  foreach ($blocks as $block) {
    $block->disable();
    $block->save();
  }
  
}